---
name: learn-bosh
director_uuid: fb70f16a-4d6f-41f8-bc2e-0181a03dff18

releases:
- name: learn-bosh
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: web
  azs: [z1]
  instances: 2
  vm_type: default
  stemcell: trusty
  networks: 
  - name: default
    static_ips:
    - 10.244.0.2
    - 10.244.0.3
  jobs:
  - name: app
    release: learn-bosh
    properties:
      port: 8888

- name: router
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: trusty
  networks: 
  - name: default
  jobs:
  - name: router
    release: learn-bosh
    properties:
      port: 8888
      servers:
      - http://10.244.0.2:8888/
      - http://10.244.0.3:8888/

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
